'use strict';
// Student activity stays in volatile memory. Bundled audio never contacts a service.
const CONTENT=/*CONTENT_DATA*/;
const AUDIO=/*AUDIO_DATA*/;
const app=document.getElementById('app'),overlay=document.getElementById('overlay');
const speaker='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M4 9v6h4l5 4V5L8 9H4Z"/><path d="M16 8a6 6 0 0 1 0 8M19 5a10 10 0 0 1 0 14"/></svg>';
const playIcon='<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="m8 4 12 8-12 8V4Z"/></svg>';
const state={screen:'home',lesson:0,practice:[],index:0,current:null,demo:false,done:false,attempts:0,assisted:false,built:[],chosen:new Set(),completed:new Set(),results:new Map(),storyDone:new Set(),story:0,question:0,storyHelp:false,storyStats:{first:0,help:0,total:0},stats:{first:0,help:0,total:0}};
let returnFocus=null,pausedForModal=false;
const audio=new Audio();audio.preload='none';let playingKey='',audioVersion=0;
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function on(id,fn){document.getElementById(id)?.addEventListener('click',fn);}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function chunks(word){return word.match(/sh|ch|th|ck|./g)||[];}
function speak(key){const id=AUDIO.lookup[key];if(!id){audioStatus('This sound is unavailable. Ask your grown-up for help.');return;}const version=++audioVersion;audio.pause();playingKey=key;audio.src=AUDIO.clips[id];const p=audio.play();if(p&&typeof p.catch==='function')p.catch(()=>{if(version===audioVersion)audioStatus('Tap the play button again to hear the sound.');});}
function stopAudio(){audioVersion++;audio.pause();playingKey='';}
function audioStatus(text){const el=document.getElementById('audioState');if(el)el.textContent=text;}
audio.addEventListener('error',()=>audioStatus('Sound could not play. Try the play button again.'));
audio.addEventListener('ended',()=>{playingKey='';});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAudio();});
function focusHeading(){const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'instant'});}
function footer(){return '<div id="audioState" class="audiostate" role="status" aria-live="polite"></div><footer class="footer"><span>No sign-in · No ads · Progress clears when this page reloads</span><button class="textbutton" id="privacy">Privacy &amp; offline copy</button></footer>';}
function common(){on('home',home);on('privacy',()=>showModal('privacy'));}
function navTop(label,progress=0,total=0){return `<div class="toprow"><button class="quiet" id="home">Lesson map</button><div class="statusbar">${total?`<div class="progress" aria-hidden="true"><span style="width:${Math.round(progress/total*100)}%"></span></div>`:''}<span>${esc(label)}</span></div></div>`;}
function home(){stopAudio();state.screen='home';state.current=null;app.innerHTML=`<section class="welcome"><div><div class="eyebrow">Listen · Build · Read</div><h1>One word at a time.</h1><p>Pick a lesson. Start with words you have learned with your grown-up.</p></div><button class="audio" id="welcome">${speaker} Hear this</button></section><div class="sectiontitle"><h2>Your reading lessons</h2><span class="visitcount">${state.completed.size} of 12 finished this visit</span></div><div class="lessonmap">${CONTENT.lessons.map((l,i)=>`<button class="lessoncard ${state.completed.has(i)?'complete':''}" data-lesson="${i}"><span class="cardhead"><span class="lessonnumber">${String(i+1).padStart(2,'0')}</span><span class="pill ${state.completed.has(i)?'done':''}">${state.completed.has(i)?'Finished today':esc(l.tag)}</span></span><strong>${esc(l.name)}</strong><span class="examples">${esc(l.examples.join(' · '))}</span></button>`).join('')}</div><p class="mapnote">All lessons are open. Your grown-up can help you choose where to start.</p>${footer()}`;app.querySelectorAll('[data-lesson]').forEach(b=>b.addEventListener('click',()=>teach(Number(b.dataset.lesson))));on('welcome',()=>speak('prompt:welcome'));common();focusHeading();}
function teach(i){stopAudio();state.lesson=i;state.screen='teach';const l=CONTENT.lessons[i];app.innerHTML=`${navTop(`Lesson ${i+1} of 12`)}<section class="panel"><div class="teachheader"><div><div class="eyebrow">${esc(l.tag)}</div><h1>${esc(l.name)}</h1><p class="task">Tap a word to hear it. Read it aloud.</p></div><div class="pattern">${esc(l.pattern)}</div></div><button class="audio" id="intro">${speaker} Hear the lesson</button><div class="wordgrid">${l.words.map(w=>`<button class="wordbutton" data-word="${w}" aria-label="Hear ${w}"><span>${w}</span>${speaker}</button>`).join('')}</div><div class="cta"><button class="primary" id="start">${playIcon} ${i===11?'Choose a story':'Try the practice'}</button>${i!==11?'<span class="small">One example, then 12 questions. No timer.</span>':'<span class="small">Read a story, then answer 3 questions.</span>'}</div></section>${footer()}`;app.querySelectorAll('[data-word]').forEach(b=>b.addEventListener('click',()=>speak('word:'+b.dataset.word)));on('intro',()=>speak('intro:'+l.id));on('start',()=>i===11?storyMenu():startPractice());common();focusHeading();speak('intro:'+l.id);}
function makeQuestion(word,mode,pool){const choices=shuffle([word,...shuffle(pool.filter(w=>w!==word)).slice(0,2)]);const parts=chunks(word);const distractors=shuffle(['a','e','i','o','u','m','n','s','t','p','f','r'].filter(c=>!parts.includes(c))).slice(0,2);return {word,mode,choices,parts,tiles:shuffle([...parts,...distractors])};}
function startPractice(){stopAudio();state.screen='practice';const l=CONTENT.lessons[state.lesson],words=shuffle(l.words);state.practice=Array.from({length:12},(_,i)=>makeQuestion(words[i%words.length],['listen','build','read'][i%3],l.words));state.index=0;state.demo=true;state.current=makeQuestion(l.words[0],'listen',l.words);state.stats={first:0,help:0,total:0};prepareQuestion();}
function prepareQuestion(){state.done=false;state.attempts=0;state.assisted=false;state.built=[];state.chosen=new Set();renderQuestion();focusHeading();playQuestion();}
function playQuestion(){const q=state.current;if(q.mode==='read')speak('prompt:read');else speak('word:'+q.word);}
function renderQuestion(){stopAudio();const q=state.current,l=CONTENT.lessons[state.lesson];const label=state.demo?'Let’s try one together':`Question ${state.index+1} of 12`;const heading=q.mode==='listen'?'Hear it. Find it.':q.mode==='build'?'Hear it. Build it.':'Read it. Match it.';const task=q.mode==='listen'?'Listen to the word. Tap the word that matches.':q.mode==='build'?'Listen to the word. Put the letters in the boxes.':'Read the word aloud. Listen to the choices and pick a match.';
app.innerHTML=`${navTop(label,state.index,12)}<section class="panel"><div class="eyebrow">${esc(l.name)} · ${state.demo?'An example':q.mode==='listen'?'Listen & find':q.mode==='build'?'Listen & build':'Read & match'}</div><h1>${heading}</h1><p class="task">${task}</p><div class="helper"><button class="audio" id="hear">${speaker} ${q.mode==='read'?'Hear the instructions':'Hear the word'}</button><button class="quiet" id="directions">Hear directions</button></div>${questionBody(q)}<div class="examplebox" id="hintbox" hidden></div><div class="feedback" id="feedback" role="status" aria-live="polite"></div><div class="cta" style="justify-content:center"><button class="quiet" id="hint">Help me</button>${q.mode==='build'?'<button class="primary" id="check">Check my word</button>':''}<button class="primary" id="next" hidden>${state.demo?'Start my 12 questions':state.index===11?'Finish practice':'Next question'}</button></div></section>${footer()}`;
on('hear',playQuestion);on('directions',()=>speak('prompt:'+q.mode));on('hint',hint);on('next',nextQuestion);on('check',checkBuild);
app.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>choose(Number(b.dataset.choice))));
app.querySelectorAll('[data-hear-choice]').forEach(b=>b.addEventListener('click',()=>speak('word:'+q.choices[Number(b.dataset.hearChoice)])));
app.querySelectorAll('[data-tile]').forEach(b=>b.addEventListener('click',()=>addTile(Number(b.dataset.tile))));
app.querySelectorAll('[data-slot]').forEach(b=>b.addEventListener('click',()=>removeSlot(Number(b.dataset.slot))));
on('clearword',clearBuild);common();if(state.demo){document.getElementById('hintbox').hidden=false;document.getElementById('hintbox').innerHTML=`<span>We’re looking for</span><strong>${q.word}</strong><button class="audio smallbtn" id="demohear">${speaker} Listen</button>`;on('demohear',()=>speak('word:'+q.word));}}
function questionBody(q){if(q.mode==='listen')return `<div class="choices">${q.choices.map((w,i)=>`<button class="wordchoice" data-choice="${i}">${w}</button>`).join('')}</div>`;if(q.mode==='build')return `<div class="buildrow" aria-label="Build the word">${q.parts.map((_,i)=>`<button class="slot empty" data-slot="${i}" aria-label="Letter box ${i+1}, empty">&nbsp;</button>`).join('')}</div><div class="tiletray">${q.tiles.map((t,i)=>`<button class="tile" data-tile="${i}" aria-label="Use ${t}">${t}</button>`).join('')}</div><div class="helper"><button class="textbutton" id="clearword">Clear the boxes</button></div>`;return `<div class="bigword">${q.word}</div><div class="soundchoices">${q.choices.map((w,i)=>`<div class="soundcard" id="soundcard${i}"><span class="soundnumber">Choice ${i+1}</span><button class="quiet" data-hear-choice="${i}" aria-label="Listen to choice ${i+1}">${speaker} Listen</button><button class="secondary" data-choice="${i}">Choose ${i+1}</button></div>`).join('')}</div>`;}
function setFeedback(text,wrong=false){const e=document.getElementById('feedback');e.textContent=text;e.className='feedback'+(wrong?' try':'');}
function hint(){if(state.done)return;state.assisted=true;const box=document.getElementById('hintbox');box.hidden=false;box.innerHTML=`<span>Read each part:</span>${state.current.parts.map(c=>`<span class="soundbox">${c}</span>`).join('')}<strong>${state.current.word}</strong>`;speak('word:'+state.current.word);setFeedback('Read the word, then try again.');}
function choose(i){if(state.done)return;const q=state.current;if(q.choices[i]===q.word){if(q.mode==='read')document.getElementById('soundcard'+i).classList.add('right');else app.querySelector(`[data-choice="${i}"]`).classList.add('right');correct();}else{state.attempts++;if(q.mode==='read')document.getElementById('soundcard'+i).classList.add('wrong');else app.querySelector(`[data-choice="${i}"]`).classList.add('wrong');setFeedback('Not quite. Listen again and try another answer.',true);speak('prompt:retry');}}
function addTile(i){if(state.done||state.chosen.has(i)||state.built.length>=state.current.parts.length)return;state.chosen.add(i);state.built.push({i,text:state.current.tiles[i]});updateBuild();}
function removeSlot(i){if(state.done||i>=state.built.length)return;state.chosen.delete(state.built[i].i);state.built.splice(i,1);updateBuild();}
function clearBuild(){if(state.done)return;state.built=[];state.chosen.clear();updateBuild();}
function updateBuild(){app.querySelectorAll('[data-slot]').forEach((b,i)=>{b.textContent=state.built[i]?.text||'\u00a0';b.classList.toggle('empty',!state.built[i]);b.setAttribute('aria-label',state.built[i]?`Remove ${state.built[i].text} from box ${i+1}`:`Letter box ${i+1}, empty`);});app.querySelectorAll('[data-tile]').forEach(b=>{b.disabled=state.chosen.has(Number(b.dataset.tile));});}
function checkBuild(){if(state.done)return;if(state.built.length!==state.current.parts.length){setFeedback('Fill the boxes, then tap check.',true);speak('prompt:empty');return;}if(state.built.map(t=>t.text).join('')===state.current.word)correct();else{state.attempts++;setFeedback('Not quite. Tap a box to change a letter, or clear the boxes.',true);speak('prompt:retry');}}
function correct(){state.done=true;if(!state.demo){state.stats.total++;if(state.attempts===0&&!state.assisted)state.stats.first++;else state.stats.help++;}app.querySelectorAll('[data-choice],[data-tile],[data-slot]').forEach(b=>b.disabled=true);document.getElementById('hint').disabled=true;const check=document.getElementById('check');if(check)check.hidden=true;setFeedback('Yes! Read the whole word aloud.');const next=document.getElementById('next');next.hidden=false;next.focus();speak('prompt:correct');}
function nextQuestion(){if(!state.done)return;stopAudio();if(state.demo){state.demo=false;state.current=state.practice[0];prepareQuestion();return;}state.index++;if(state.index>=12){state.completed.add(state.lesson);state.results.set(state.lesson,{...state.stats});practiceFinish();return;}state.current=state.practice[state.index];prepareQuestion();}
function practiceFinish(){state.screen='finish';const l=CONTENT.lessons[state.lesson];app.innerHTML=`${navTop('Practice finished',12,12)}<section class="panel center"><div class="finishmark">12 questions. Nice work!</div><h1>${esc(l.name)} practice finished.</h1><p class="sub" style="margin:16px auto">Some words take another try. That’s part of practice.</p><div class="summarygrid"><div class="summarycell"><strong>${state.stats.total}</strong><span>Questions finished</span></div><div class="summarycell"><strong>${state.stats.first}</strong><span>First-try matches</span></div><div class="summarycell"><strong>${state.stats.help}</strong><span>With another try or a hint</span></div></div><div class="cta" style="justify-content:center"><button class="primary" id="continue">Try the next lesson</button><button class="quiet" id="again">Practise these words again</button></div><p class="small" style="margin-top:22px">Your grown-up can help decide what to practise next.</p></section>${footer()}`;on('continue',()=>teach(Math.min(state.lesson+1,11)));on('again',startPractice);common();focusHeading();speak('prompt:finish');}
function storyMenu(){stopAudio();state.screen='story-menu';app.innerHTML=`${navTop('Little stories')}<section class="panel"><div class="eyebrow">Read and understand</div><h1>Pick a little story.</h1><p class="task">Read the story aloud. Then answer three questions.</p><div class="stories">${CONTENT.stories.map((s,i)=>`<button class="storycard" data-story="${i}"><strong>${esc(s.title)}</strong><span>${state.storyDone.has(i)?'Finished this visit':'4 short sentences · 3 questions'}</span></button>`).join('')}</div><p class="small">Ask your grown-up to help with the words listed for each story.</p></section>${footer()}`;app.querySelectorAll('[data-story]').forEach(b=>b.addEventListener('click',()=>startStory(Number(b.dataset.story))));common();focusHeading();}
function startStory(i){state.story=i;state.question=0;state.storyHelp=false;state.storyStats={first:0,help:0,total:0};state.screen='story';prepareStoryQuestion();}
function prepareStoryQuestion(){stopAudio();state.done=false;state.attempts=0;state.assisted=state.storyHelp;renderStory();focusHeading();speak(`question:${state.story}:${state.question}`);}
function renderStory(){const s=CONTENT.stories[state.story],q=s.questions[state.question];app.innerHTML=`${navTop(`Question ${state.question+1} of 3`,state.question,3)}<section class="panel"><div class="eyebrow">Little stories</div><h1>${esc(s.title)}</h1><div class="helper" style="justify-content:flex-start"><button class="audio" id="listenstory">${speaker} Listen to the story</button><button class="quiet" id="storydirections">Hear directions</button></div><p class="small">${esc(s.preview)}</p><div class="storytext">${s.lines.map(t=>`<p>${esc(t)}</p>`).join('')}</div><div class="question">${esc(q.q)} <button class="audio smallbtn" id="hearquestion" aria-label="Hear the question">${speaker}</button></div><div class="answers">${q.answers.map((a,i)=>`<div class="answerbox"><button class="answer" data-answer="${i}">${esc(a)}</button><button class="playanswer" data-play-answer="${i}" aria-label="Hear answer ${i+1}">${speaker} Hear it</button></div>`).join('')}</div><div class="feedback" id="feedback" role="status" aria-live="polite"></div><div class="cta" style="justify-content:center"><button class="quiet" id="storyhint">Help me find it</button><button class="primary" id="storynext" hidden>${state.question===2?'Finish story':'Next question'}</button></div></section>${footer()}`;
on('listenstory',()=>{state.storyHelp=true;state.assisted=true;speak('story:'+state.story);});on('storydirections',()=>speak('prompt:story-directions'));on('hearquestion',()=>speak(`question:${state.story}:${state.question}`));on('storyhint',()=>{state.assisted=true;setFeedback('Read the story again. Find the part that tells you.');speak('prompt:story-retry');});app.querySelectorAll('[data-play-answer]').forEach(b=>b.addEventListener('click',()=>speak(`answer:${state.story}:${state.question}:${b.dataset.playAnswer}`)));app.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answerStory(Number(b.dataset.answer))));on('storynext',nextStoryQuestion);common();}
function answerStory(i){if(state.done)return;const q=CONTENT.stories[state.story].questions[state.question],b=app.querySelector(`[data-answer="${i}"]`);if(i!==q.correct){state.attempts++;b.classList.add('wrong');setFeedback('Look in the story and try again.',true);speak('prompt:story-retry');return;}b.classList.add('right');state.done=true;state.storyStats.total++;if(state.attempts===0&&!state.assisted)state.storyStats.first++;else state.storyStats.help++;app.querySelectorAll('[data-answer]').forEach(el=>el.disabled=true);document.getElementById('storyhint').disabled=true;setFeedback('Yes! The story tells you that.');document.getElementById('storynext').hidden=false;document.getElementById('storynext').focus();speak('prompt:story-correct');}
function nextStoryQuestion(){if(!state.done)return;stopAudio();state.question++;if(state.question<3){prepareStoryQuestion();return;}state.storyDone.add(state.story);if(state.storyDone.size===CONTENT.stories.length)state.completed.add(11);state.results.set('story'+state.story,{...state.storyStats});state.screen='story-finish';app.innerHTML=`${navTop('Story finished',3,3)}<section class="panel center"><div class="finishmark">Story finished!</div><h1>You read ${esc(CONTENT.stories[state.story].title)}.</h1><p class="sub" style="margin:16px auto">Tell your grown-up what happened in your own words.</p><div class="summarygrid"><div class="summarycell"><strong>3</strong><span>Questions finished</span></div><div class="summarycell"><strong>${state.storyStats.first}</strong><span>First-try matches</span></div><div class="summarycell"><strong>${state.storyStats.help}</strong><span>With help or another try</span></div></div><div class="cta" style="justify-content:center"><button class="primary" id="otherstory">Choose another story</button><button class="quiet" id="storyagain">Read this story again</button></div></section>${footer()}`;on('otherstory',storyMenu);on('storyagain',()=>startStory(state.story));common();focusHeading();speak('prompt:finish');}
function privacyHTML(){return `<p><strong>No student names, accounts, recordings, or answers are sent anywhere by this app.</strong></p><ul><li>No sign-in, text-entry fields, cookies, saved browser data, tracking, ads, external fonts or scripts.</li><li>Lesson choices, answers and first-try counts are processed in this page’s memory. They disappear when the page reloads or closes.</li><li>The spoken words and instructions are prerecorded synthetic audio bundled in this file. Nothing is sent to a voice service, and the microphone is never used.</li><li>After this file loads, practice makes no network requests.</li></ul><h2>Website hosting</h2><p>GitHub Pages receives the request to load this page and logs visitors’ IP addresses for security. Hosting is outside the app’s control, so the online version does not promise that absolutely no information is collected.</p><h2>Use it offline</h2><p>Download a copy, then open the HTML file in a browser. Every lesson and sound is included. You can disconnect from the internet and still practise.</p><button class="primary" id="download">Download offline copy</button><p class="small">The downloaded copy contains the app, lessons and audio, with no answers or progress from this visit. Devices, browsers, extensions and school management systems may have their own activity logging.</p>`;}
function teacherHTML(){const rows=[...state.results.entries()].map(([id,r])=>{const label=typeof id==='number'?CONTENT.lessons[id].name:CONTENT.stories[Number(id.slice(5))].title;return `<tr><td>${esc(label)}</td><td>${r.total}</td><td>${r.first}</td><td>${r.help}</td></tr>`;}).join('');return `<p>An original, free reading-practice app. Match its word groups to skills the learner has already been taught.</p><div class="notice"><strong>Start with your teaching sequence.</strong> All lessons are open. The app does not diagnose reading difficulties or decide that a child has mastered a skill.</div><h2>What the activities check</h2><ul><li><strong>Hear &amp; find:</strong> matching a spoken word to its spelling.</li><li><strong>Hear &amp; build:</strong> arranging letter or digraph tiles to spell a spoken word.</li><li><strong>Read &amp; match:</strong> reading a printed word and selecting its matching spoken form.</li><li><strong>Little stories:</strong> answering three literal comprehension questions with the passage available.</li></ul><p>Each word lesson has a spoken introduction, example words, one guided question and 12 mixed practice questions. Short vowel lessons assume the child knows the consonant letter sounds. Blending and oral reading still benefit from adult observation.</p><h2>This visit only</h2><p>These are activity counts, not reading levels or diagnostic scores. A first-try match means the first submitted answer was correct without revealing the target. Another try or a hint moves it into the help column. Story audio counts as help for that question and subsequent questions.</p>${rows?`<div class="reportwrap"><table><thead><tr><th>Practice</th><th>Finished</th><th>First try</th><th>With help / retry</th></tr></thead><tbody>${rows}</tbody></table></div>`:'<p class="small">No practice has been finished during this visit.</p>'}<h2>For teacher review</h2><p>Check the letter patterns, vocabulary, pronunciation and lesson order. The North American synthetic voice reads whole words and instructions; it does not model isolated phonemes. Story passages include preview words and patterns beyond a single lesson and are not aligned to a specific programme’s decodable sequence.</p><p>This app has not been evaluated as a reading intervention. Teacher feedback should guide its use and future lessons.</p><h2>Useful feedback</h2><p>Which patterns should come first? What errors need more explanation? Which word lists and stories fit your lessons? Which activities work without adult help?</p><details><summary>Privacy &amp; offline copy</summary>${privacyHTML()}</details><details><summary>Audio credits</summary><p>Original lesson recordings were generated locally using CMU Flite and its SLT voice. No speech service runs during use.</p><pre class="licence">/*AUDIO_CREDIT*/</pre></details><button class="quiet" id="resetvisit">Clear this visit’s practice</button>`;}
function showModal(tab){returnFocus=document.activeElement;stopAudio();overlay.hidden=false;overlay.className='backdrop';overlay.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><div class="toprow"><span class="pill">Reading Room · version 1.0</span><button class="quiet" id="closemodal">Close</button></div><h1 id="modalTitle">${tab==='privacy'?'Privacy & offline use':'For grown-ups'}</h1>${tab==='privacy'?privacyHTML():teacherHTML()}</section>`;document.body.style.overflow='hidden';on('closemodal',closeModal);on('download',downloadCopy);on('resetvisit',()=>{state.completed.clear();state.results.clear();state.storyDone.clear();closeModal();home();});document.getElementById('closemodal').focus();}
function closeModal(){overlay.hidden=true;overlay.innerHTML='';document.body.style.overflow='';returnFocus?.focus();}
function downloadCopy(){const clone=document.documentElement.cloneNode(true);clone.querySelector('#app').innerHTML='';clone.querySelector('#overlay').innerHTML='';clone.querySelector('#overlay').hidden=true;clone.querySelector('#overlay').removeAttribute('class');clone.querySelector('body').removeAttribute('style');const blob=new Blob(['<!doctype html>\n'+clone.outerHTML],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='reading-room-offline.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
document.getElementById('teacher').addEventListener('click',()=>showModal('teacher'));
overlay.addEventListener('click',e=>{if(e.target===overlay)closeModal();});
document.addEventListener('keydown',e=>{if(overlay.hidden)return;if(e.key==='Escape'){e.preventDefault();closeModal();}if(e.key==='Tab'){const f=[...overlay.querySelectorAll('button,summary')].filter(el=>el.getClientRects().length),first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
home();
