// A single guided next step, plus a private, resumable starting check.
const guided={busy:false,pending:null,preview:false};
const priorCodeScreen=codeScreen;
codeScreen=function(){guided.preview=false;priorCodeScreen();const entry=document.getElementById('openpractice');if(entry)entry.textContent='Browse all lessons';const preview=document.createElement('button');preview.className='secondary';preview.id='previewcheck';preview.textContent='Try the starting check without a code';preview.addEventListener('click',()=>{guided.preview=true;connected.profile={readerNumber:0,plan:[],planVersion:1,completed:[],completedStories:[],practiceStatus:[],placement:{generation:1,status:'pending',answers:[],result:null}};guided.pending=null;startingIntro();});entry?.parentNode?.append(preview);};
const priorLoginLearner=loginLearner;
loginLearner=async function(){guided.preview=false;guided.pending=null;await priorLoginLearner();};
home=function(){if(connected.token||guided.preview)return assignedHome();if(classroomEnabled())return codeScreen();return openHome();};
function guidedActive(){return !!connected.token||guided.preview;}
function startingIntro(){stopAudio();connected.run=null;state.current=null;state.screen='placement-intro';const p=connected.profile,count=p.placement.answers.length;app.innerHTML=`<section class="panel"><div class="eyebrow">Find your starting point</div><h1>${count?'Let’s keep going.':'A small check. Then your practice.'}</h1><p class="task">Listen, read, and choose one answer at a time.</p><div class="guide-steps"><div><strong>1 · Try a few questions</strong><span>No timer. Choose “Not sure” when you need to.</span></div><div><strong>2 · Get a starting lesson</strong><span>We’ll pick some practice to try. Your teacher can change it.</span></div><div><strong>3 · Learn and practise</strong><span>One lesson at a time, with help when you need it.</span></div></div><p class="small">12–28 questions, depending on your answers. You can stop and return later.${guided.preview?' This preview stays in this tab and clears on reload.':' Your code saves your place.'}</p><p class="notice">Check that you can hear the words. Ask a grown-up to read the directions if needed. They should let you choose your own answers.</p><div class="cta"><button class="audio" id="checksound">${speaker} Check the sound</button><button class="primary" id="begincheck">${count?'Continue the check':'Start the check'}</button></div><p id="checkmessage" role="status" aria-live="polite"></p></section>${footer()}`;on('checksound',()=>speak('placement:soundcheck'));on('begincheck',beginStartingCheck);common();focusHeading();}
async function beginStartingCheck(){if(guided.busy)return;guided.busy=true;const b=document.getElementById('begincheck');if(b)b.disabled=true;try{if(!guided.preview)connected.profile=await classroomAPI('placement/start','POST',{planVersion:connected.profile.planVersion});renderStartingQuestion();}catch(e){if(e.status===409){try{return await recoverStartingChange();}catch{}}document.getElementById('checkmessage').textContent=e.message;}finally{guided.busy=false;if(b)b.disabled=false;}}
function renderStartingQuestion(){stopAudio();state.screen='placement';connected.run=null;const answers=connected.profile.placement.answers,q=Placement.next(answers);if(!q)return startingFinished();const soundChoices=q.kind==='read'||q.kind==='sound',textHelp=['meaning','listening','sound'].includes(q.kind);app.innerHTML=`<div class="toprow"><button class="quiet" id="home">Pause the check</button><span class="small">Question ${answers.length+1} · No timer</span></div><section class="panel"><div class="eyebrow">${q.kind==='listening'?'Listen to a short story':q.kind==='reading'?'Read a short passage':'Find your starting point'}</div><h1>${q.kind==='read'?'Read it. Match its sound.':q.kind==='listen'?'Hear it. Find the word.':q.kind==='sound'?'Listen and choose.':q.kind==='reading'?'Read and think.':'Listen and think.'}</h1>${q.kind==='reading'?`<div class="storytext"><p>${esc(q.passage)}</p></div>`:''}<p class="task">${esc(q.prompt)}</p>${q.kind==='read'?`<div class="bigword">${esc(q.word)}</div><button class="audio" id="checkhear">${speaker} Hear the instructions</button>`:`<button class="audio" id="checkhear">${speaker} ${q.kind==='listen'?'Hear the word':q.kind==='listening'?'Hear the story and question':q.kind==='reading'?'Hear only the question':'Hear the question'}</button>`}${soundChoices?`<div class="soundchoices">${q.choices.map((_,i)=>`<div class="soundcard"><span class="soundnumber">Choice ${i+1}</span><button class="quiet" data-check-hear="${i}">${speaker} Listen</button><button class="secondary" data-check-answer="${i}">Choose ${i+1}</button></div>`).join('')}</div>`:`<div class="answers">${q.choices.map((c,i)=>`<div class="answerbox"><button class="wordchoice meaningchoice" data-check-answer="${i}">${esc(c)}</button>${textHelp?`<button class="playanswer" data-check-hear="${i}" aria-label="Hear answer ${i+1}">${speaker} Hear it</button>`:''}</div>`).join('')}</div>`}<div class="cta"><button class="quiet" id="notsure">Not sure · Move on</button><button class="primary" id="retrycheck" hidden>Retry saving this answer</button></div><p id="checkmessage" role="status" aria-live="polite">Choose once. You’ll get a starting lesson when the check is finished.</p></section>${footer()}`;on('checkhear',()=>speak(q.kind==='listen'?'word:'+q.word:q.kind==='read'?'placement:readinstructions':'placement:question:'+q.id));app.querySelectorAll('[data-check-hear]').forEach(b=>b.addEventListener('click',()=>speak(q.kind==='read'?'word:'+q.choices[Number(b.dataset.checkHear)]:'placement:choice:'+q.id+':'+b.dataset.checkHear)));app.querySelectorAll('[data-check-answer]').forEach(b=>b.addEventListener('click',()=>answerStartingCheck(q.id,Number(b.dataset.checkAnswer))));on('notsure',()=>answerStartingCheck(q.id,-1));on('retrycheck',submitStartingAnswer);common();focusHeading();}
function lockStartingAnswers(){app.querySelectorAll('[data-check-answer]').forEach(b=>b.disabled=true);const skip=document.getElementById('notsure');if(skip)skip.disabled=true;}
function answerStartingCheck(itemId,answer){if(guided.busy||guided.pending)return;guided.pending={itemId,answer,generation:connected.profile.placement.generation,planVersion:connected.profile.planVersion};lockStartingAnswers();submitStartingAnswer();}
async function submitStartingAnswer(){if(guided.busy||!guided.pending)return;guided.busy=true;lockStartingAnswers();const message=document.getElementById('checkmessage'),retry=document.getElementById('retrycheck');if(message)message.textContent=guided.preview?'Keeping your answer…':'Saving your answer…';if(retry){retry.hidden=true;retry.disabled=true;}try{const payload=guided.pending;if(guided.preview){const p=connected.profile;const clean=Placement.validate([...p.placement.answers,{id:payload.itemId,answer:payload.answer}]);p.placement.answers=clean;if(!Placement.next(clean)){const result=Placement.result(clean);p.placement.status='complete';p.placement.result=result;p.plan=result.plan;p.planVersion++;}}else{connected.profile=await classroomAPI('placement','PUT',payload);}guided.pending=null;saveNotice(guided.preview?'Preview · Nothing saved online':'Your starting check is saved.');if(connected.profile.placement.status==='complete')startingFinished();else renderStartingQuestion();}catch(e){if(e.status===409){try{return await recoverStartingChange();}catch{}}if(message)message.textContent='Not saved yet. Keep this tab open. '+e.message;if(retry){retry.hidden=false;retry.disabled=false;}}finally{guided.busy=false;}}
async function recoverStartingChange(){connected.profile=await classroomAPI('me');guided.pending=null;saveNotice('Your practice changed. Here is your current starting point.');assignedHome();}
function startingFinished(){stopAudio();state.screen='placement-finish';const first=CONTENT.lessons.find(l=>l.id===connected.profile.plan[0]);app.innerHTML=`<section class="panel center"><div class="finishmark">Starting check finished</div><h1>Let’s begin with ${esc(first?.name||'your next lesson')}.</h1><p class="task">First we’ll learn together. Then you’ll try the practice.</p><p>Your teacher can review this starting point and change it.</p><div class="cta"><button class="primary" id="beginrecommended">Start my lesson</button><button class="quiet" id="home">Take a break</button></div>${guided.preview?'<p class="small">Preview only. These answers and the plan clear when this page reloads.</p>':''}</section>${footer()}`;on('beginrecommended',()=>startGuidedLesson(first.id));common();focusHeading();}
assignedHome=function(){stopAudio();state.screen='home';state.current=null;const p=connected.profile;if(!p)return codeScreen();if(p.placement?.status==='pending')return startingIntro();const next=Placement.nextPractice(p),l=CONTENT.lessons.find(l=>l.id===next.lessonId),finished=next.kind==='finished';app.innerHTML=`<section class="welcome"><div><div class="eyebrow">${guided.preview?'Try Reading Room · This tab only':'Your reading practice'}</div><h1>${finished?'Your practice plan is finished.':'Your next small step.'}</h1><p>${finished?'You can revisit a lesson while your teacher chooses what comes next.':next.kind==='review'?'Let’s revisit these words before moving on.':next.kind==='resume'?'Pick up where you stopped.':'One lesson at a time. Listen, learn, and practise.'}</p></div></section>${l?`<section class="panel guide-next"><span class="pill">${finished?'Review':next.kind==='review'?'A little more practice':next.kind==='resume'?'Keep going':'Up next'}</span><h2>${esc(l.name)}</h2><p>${esc(l.examples?.join(' · ')||l.stage)}</p><div class="guide-steps"><div><strong>Learn</strong><span>Hear the explanation and examples.</span></div><div><strong>Try</strong><span>${l.kind==='stories'?'Read and reread a story.':'Try 12 questions, with help if needed.'}</span></div><div><strong>Review</strong><span>Revisit words that need another try.</span></div></div><button class="primary" id="guidedstart">${next.kind==='resume'?'Keep going':l.kind==='stories'?'Read my next story':finished?'Revisit this lesson':'Start my practice'}</button></section>`:'<p class="notice">Your teacher is getting your practice ready.</p>'}<details class="panel"><summary>See my practice plan · ${p.completed.filter(id=>p.plan.includes(id)).length} of ${p.plan.length} lessons practised</summary><div class="lessonmap" style="margin-top:16px">${p.plan.map(id=>{const i=CONTENT.lessons.findIndex(l=>l.id===id),l=CONTENT.lessons[i];return `<button class="lessoncard" data-assigned="${i}"><strong>${esc(l.name)}</strong><span class="examples">${p.completed.includes(id)?'Practised':esc(l.stage)}</span></button>`;}).join('')}</div></details>${!guided.preview?'<button class="quiet" id="refreshplan">Check for a new plan</button>':''}${footer()}`;on('guidedstart',()=>next.kind==='resume'?resumeRun():startGuidedLesson(l.id));on('refreshplan',refreshPlan);app.querySelectorAll('[data-assigned]').forEach(b=>b.addEventListener('click',()=>startGuidedLesson(CONTENT.lessons[Number(b.dataset.assigned)].id)));common();focusHeading();};
function startGuidedLesson(id){const i=CONTENT.lessons.findIndex(l=>l.id===id);if(i<0)return assignedHome();if(CONTENT.lessons[i].kind==='stories'){const done=new Set(connected.profile.completedStories||[]);const next=CONTENT.stories.findIndex((_,j)=>!done.has(j));startStory(next<0?0:next);}else teach(i);}
const priorNavTop=navTop;navTop=function(...args){return priorNavTop(...args).replace('Lesson map',guidedActive()?'My practice':'Lesson map');};
const priorPracticeFinish=practiceFinish;
practiceFinish=function(){if(!guidedActive())return priorPracticeFinish();state.screen='finish';const l=CONTENT.lessons[state.lesson];app.innerHTML=`${navTop('Practice finished',12,12)}<section class="panel center"><div class="finishmark">You finished your practice.</div><h1>One more small step taken.</h1><p class="task">${esc(l.name)}</p><p>${state.stats.help>=4?'These words need another look. Your next step will include more practice.':'You can continue your plan or take a break.'}</p>${state.stats.review?`<p>You also revisited ${state.stats.review} review questions.</p>`:''}<div class="cta"><button class="primary" id="continueguide">See my next step</button><button class="quiet" id="home">Take a break</button></div></section>${footer()}`;if(guided.preview){const p=connected.profile,id=l.id;p.lastCompletedLessonId=id;if(!p.completed.includes(id))p.completed.push(id);const old=p.practiceStatus.find(s=>s.lessonId===id);p.practiceStatus=p.practiceStatus.filter(s=>s.lessonId!==id);p.practiceStatus.push({lessonId:id,finishedRuns:(old?.finishedRuns||0)+1,needsSupport:state.stats.help>=4,firstTry:state.stats.first,total:state.stats.total});}on('continueguide',returnToGuide);common();focusHeading();};
async function returnToGuide(){if(guided.preview)return assignedHome();markProgress();await flushProgress();if(connected.pending.size){saveNotice('Keep this page open and retry saving before moving on.');return;}try{connected.profile=await classroomAPI('me');connected.run=null;assignedHome();}catch(e){saveNotice(e.message);}}
const priorRefreshPlan=refreshPlan;
refreshPlan=async function(){if(guided.pending){await submitStartingAnswer();if(guided.pending)return;}await priorRefreshPlan();};
const priorSignOut=signOutLearner;
signOutLearner=async function(){if(guided.pending){await submitStartingAnswer();if(guided.pending)return;}guided.preview=false;await priorSignOut();};
common=function(){on('privacy',()=>showModal('privacy'));on('codeentry',codeScreen);on('signout',signOutLearner);on('home',async()=>{if(!guidedActive())return home();if(guided.pending){await submitStartingAnswer();if(guided.pending)return;}if(connected.token&&['finish','story-finish'].includes(state.screen))return returnToGuide();if(connected.token&&['practice','story','story-read'].includes(state.screen)){markProgress();await flushProgress();if(connected.pending.size)return;}assignedHome();});};
// Story completion uses the same simple next-step flow.
const priorGuidedNextStory=nextStoryQuestion;
nextStoryQuestion=function(){priorGuidedNextStory();if(guidedActive()&&state.screen==='story-finish'){const primary=document.getElementById('otherstory');if(primary){const replacement=document.createElement('button');replacement.className='primary';replacement.textContent='See my next step';replacement.addEventListener('click',returnToGuide);primary.replaceWith(replacement);}if(guided.preview){const p=connected.profile;p.lastCompletedLessonId='stories';if(!p.completedStories.includes(state.story))p.completedStories.push(state.story);if(p.completedStories.length===CONTENT.stories.length&&!p.completed.includes('stories'))p.completed.push('stories');}}};
const priorGuidedTeacherHTML=teacherHTML;
teacherHTML=function(){return priorGuidedTeacherHTML().replace('There is no automatic mastery claim, placement diagnosis, hidden level lock, or saved student profile.','The starting check suggests practice from original questions. It is not a validated assessment, diagnosis or mastery claim.').replace('or automatic student placement','or automatic diagnosis').replace('<h2>What the activities check</h2>','<h2>Starting check and guided practice</h2><p>The optional starting check covers word patterns, word parts, listening comprehension, and short-passage comprehension when appropriate. It suggests a small practice plan; teachers can change it. A reader who uses a code saves their check and resumes it after logging in again. A preview without a code stays in this tab.</p><h2>What the activities check</h2>');};
